// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: blockchain.proto

package blockchain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_Tron   AccountType = 0
	AccountType_Ton    AccountType = 1
	AccountType_Solana AccountType = 2
	AccountType_Bsc    AccountType = 3
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "Tron",
		1: "Ton",
		2: "Solana",
		3: "Bsc",
	}
	AccountType_value = map[string]int32{
		"Tron":   0,
		"Ton":    1,
		"Solana": 2,
		"Bsc":    3,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_blockchain_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{0}
}

// 操作枚举
type APIEnum int32

const (
	// todo
	APIEnum_SendTx APIEnum = 0
)

// Enum value maps for APIEnum.
var (
	APIEnum_name = map[int32]string{
		0: "SendTx",
	}
	APIEnum_value = map[string]int32{
		"SendTx": 0,
	}
)

func (x APIEnum) Enum() *APIEnum {
	p := new(APIEnum)
	*p = x
	return p
}

func (x APIEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APIEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_proto_enumTypes[1].Descriptor()
}

func (APIEnum) Type() protoreflect.EnumType {
	return &file_blockchain_proto_enumTypes[1]
}

func (x APIEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use APIEnum.Descriptor instead.
func (APIEnum) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{1}
}

type AddressType int32

const (
	AddressType_receive AddressType = 0
	AddressType_gather  AddressType = 1
)

// Enum value maps for AddressType.
var (
	AddressType_name = map[int32]string{
		0: "receive",
		1: "gather",
	}
	AddressType_value = map[string]int32{
		"receive": 0,
		"gather":  1,
	}
)

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}

func (x AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_proto_enumTypes[2].Descriptor()
}

func (AddressType) Type() protoreflect.EnumType {
	return &file_blockchain_proto_enumTypes[2]
}

func (x AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressType.Descriptor instead.
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{2}
}

type BlockchainNetwork struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Uid                 uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                           // 网络唯一id
	Key                 string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                            // 网络唯一key
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                          // 网络名
	ChainID             string                 `protobuf:"bytes,4,opt,name=chainID,proto3" json:"chainID,omitempty"`                                    // chainID
	AccountKey          AccountType            `protobuf:"varint,5,opt,name=accountKey,proto3,enum=blockchain.AccountType" json:"accountKey,omitempty"` // 网络账号类型
	Decimal             uint64                 `protobuf:"varint,6,opt,name=decimal,proto3" json:"decimal,omitempty"`                                   // 原生币精度
	DisplayDecimal      uint64                 `protobuf:"varint,7,opt,name=displayDecimal,proto3" json:"displayDecimal,omitempty"`                     // 原生币展示精度
	Logo                string                 `protobuf:"bytes,8,opt,name=logo,proto3" json:"logo,omitempty"`                                          // logo
	Symbol              string                 `protobuf:"bytes,9,opt,name=symbol,proto3" json:"symbol,omitempty"`                                      // 原生币名
	FullSymbol          string                 `protobuf:"bytes,10,opt,name=fullSymbol,proto3" json:"fullSymbol,omitempty"`                             // 原生币全名
	ArchType            string                 `protobuf:"bytes,11,opt,name=archType,proto3" json:"archType,omitempty"`                                 //  技术底层evm，cosmos。。。
	RpcURL              []string               `protobuf:"bytes,12,rep,name=rpcURL,proto3" json:"rpcURL,omitempty"`                                     // rpc url
	ConfirmStrategy     uint64                 `protobuf:"varint,13,opt,name=confirmStrategy,proto3" json:"confirmStrategy,omitempty"`                  // 确认策略
	BlockGenerationRate uint64                 `protobuf:"varint,14,opt,name=blockGenerationRate,proto3" json:"blockGenerationRate,omitempty"`          // 出块时间
	ScanURL             string                 `protobuf:"bytes,15,opt,name=scanURL,proto3" json:"scanURL,omitempty"`                                   //浏览器地址
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BlockchainNetwork) Reset() {
	*x = BlockchainNetwork{}
	mi := &file_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainNetwork) ProtoMessage() {}

func (x *BlockchainNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainNetwork.ProtoReflect.Descriptor instead.
func (*BlockchainNetwork) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainNetwork) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BlockchainNetwork) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlockchainNetwork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlockchainNetwork) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

func (x *BlockchainNetwork) GetAccountKey() AccountType {
	if x != nil {
		return x.AccountKey
	}
	return AccountType_Tron
}

func (x *BlockchainNetwork) GetDecimal() uint64 {
	if x != nil {
		return x.Decimal
	}
	return 0
}

func (x *BlockchainNetwork) GetDisplayDecimal() uint64 {
	if x != nil {
		return x.DisplayDecimal
	}
	return 0
}

func (x *BlockchainNetwork) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *BlockchainNetwork) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BlockchainNetwork) GetFullSymbol() string {
	if x != nil {
		return x.FullSymbol
	}
	return ""
}

func (x *BlockchainNetwork) GetArchType() string {
	if x != nil {
		return x.ArchType
	}
	return ""
}

func (x *BlockchainNetwork) GetRpcURL() []string {
	if x != nil {
		return x.RpcURL
	}
	return nil
}

func (x *BlockchainNetwork) GetConfirmStrategy() uint64 {
	if x != nil {
		return x.ConfirmStrategy
	}
	return 0
}

func (x *BlockchainNetwork) GetBlockGenerationRate() uint64 {
	if x != nil {
		return x.BlockGenerationRate
	}
	return 0
}

func (x *BlockchainNetwork) GetScanURL() string {
	if x != nil {
		return x.ScanURL
	}
	return ""
}

type GenAddressReq struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccountType AccountType            `protobuf:"varint,1,opt,name=accountType,proto3,enum=blockchain.AccountType" json:"accountType,omitempty"`
	AddressType AddressType            `protobuf:"varint,2,opt,name=addressType,proto3,enum=blockchain.AddressType" json:"addressType,omitempty"`
	Bid         string                 `protobuf:"bytes,3,opt,name=bid,proto3" json:"bid,omitempty"`
	Nums          int64                  `protobuf:"varint,4,opt,name=nums,proto3" json:"nums,omitempty"`
	WithUSDT      bool                   `protobuf:"varint,5,opt,name=withUSDT,proto3" json:"withUSDT,omitempty"`
	NetworkKey    string                 `protobuf:"bytes,6,opt,name=networkKey,proto3" json:"networkKey,omitempty"`
	TokenKind     string                 `protobuf:"bytes,7,opt,name=tokenKind,proto3" json:"tokenKind,omitempty"` // solana 地址与币种绑定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenAddressReq) Reset() {
	*x = GenAddressReq{}
	mi := &file_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAddressReq) ProtoMessage() {}

func (x *GenAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenAddressReq.ProtoReflect.Descriptor instead.
func (*GenAddressReq) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *GenAddressReq) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_Tron
}

func (x *GenAddressReq) GetAddressType() AddressType {
	if x != nil {
		return x.AddressType
	}
	return AddressType_receive
}

func (x *GenAddressReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GenAddressReq) GetNums() int64 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *GenAddressReq) GetWithUSDT() bool {
	if x != nil {
		return x.WithUSDT
	}
	return false
}

func (x *GenAddressReq) GetNetworkKey() string {
	if x != nil {
		return x.NetworkKey
	}
	return ""
}

func (x *GenAddressReq) GetTokenKind() string {
	if x != nil {
		return x.TokenKind
	}
	return ""
}

type GenAddressRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []string               `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenAddressRes) Reset() {
	*x = GenAddressRes{}
	mi := &file_blockchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAddressRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAddressRes) ProtoMessage() {}

func (x *GenAddressRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenAddressRes.ProtoReflect.Descriptor instead.
func (*GenAddressRes) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *GenAddressRes) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

type CollectFundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkKey    string                 `protobuf:"bytes,1,opt,name=networkKey,proto3" json:"networkKey,omitempty"`
	TokenID       uint64                 `protobuf:"varint,2,opt,name=tokenID,proto3" json:"tokenID,omitempty"`
	Send          []string               `protobuf:"bytes,3,rep,name=send,proto3" json:"send,omitempty"`
	Receive       string                 `protobuf:"bytes,4,opt,name=receive,proto3" json:"receive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectFundReq) Reset() {
	*x = CollectFundReq{}
	mi := &file_blockchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectFundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFundReq) ProtoMessage() {}

func (x *CollectFundReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFundReq.ProtoReflect.Descriptor instead.
func (*CollectFundReq) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *CollectFundReq) GetNetworkKey() string {
	if x != nil {
		return x.NetworkKey
	}
	return ""
}

func (x *CollectFundReq) GetTokenID() uint64 {
	if x != nil {
		return x.TokenID
	}
	return 0
}

func (x *CollectFundReq) GetSend() []string {
	if x != nil {
		return x.Send
	}
	return nil
}

func (x *CollectFundReq) GetReceive() string {
	if x != nil {
		return x.Receive
	}
	return ""
}

type CollectFundRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []string               `protobuf:"bytes,1,rep,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectFundRes) Reset() {
	*x = CollectFundRes{}
	mi := &file_blockchain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectFundRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFundRes) ProtoMessage() {}

func (x *CollectFundRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFundRes.ProtoReflect.Descriptor instead.
func (*CollectFundRes) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{4}
}

func (x *CollectFundRes) GetTxHash() []string {
	if x != nil {
		return x.TxHash
	}
	return nil
}

type SendToReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkKey    string                 `protobuf:"bytes,1,opt,name=networkKey,proto3" json:"networkKey,omitempty"`
	TokenID       uint64                 `protobuf:"varint,2,opt,name=tokenID,proto3" json:"tokenID,omitempty"`
	Send          string                 `protobuf:"bytes,3,opt,name=send,proto3" json:"send,omitempty"`
	Receive       string                 `protobuf:"bytes,4,opt,name=receive,proto3" json:"receive,omitempty"`
	Amount        uint64                 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	IsOut         bool                   `protobuf:"varint,6,opt,name=isOut,proto3" json:"isOut,omitempty"` // to 是否为外部地址
	BusinessType  string                 `protobuf:"bytes,7,opt,name=businessType,proto3" json:"businessType,omitempty"`
	ForceSend     bool                   `protobuf:"varint,8,opt,name=forceSend,proto3" json:"forceSend,omitempty"`
	Memo          string                 `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`      // 某些网络的备注
	BillID        string                 `protobuf:"bytes,10,opt,name=billID,proto3" json:"billID,omitempty"` // 账单ID，
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToReq) Reset() {
	*x = SendToReq{}
	mi := &file_blockchain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToReq) ProtoMessage() {}

func (x *SendToReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToReq.ProtoReflect.Descriptor instead.
func (*SendToReq) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{5}
}

func (x *SendToReq) GetNetworkKey() string {
	if x != nil {
		return x.NetworkKey
	}
	return ""
}

func (x *SendToReq) GetTokenID() uint64 {
	if x != nil {
		return x.TokenID
	}
	return 0
}

func (x *SendToReq) GetSend() string {
	if x != nil {
		return x.Send
	}
	return ""
}

func (x *SendToReq) GetReceive() string {
	if x != nil {
		return x.Receive
	}
	return ""
}

func (x *SendToReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SendToReq) GetIsOut() bool {
	if x != nil {
		return x.IsOut
	}
	return false
}

func (x *SendToReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *SendToReq) GetForceSend() bool {
	if x != nil {
		return x.ForceSend
	}
	return false
}

func (x *SendToReq) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *SendToReq) GetBillID() string {
	if x != nil {
		return x.BillID
	}
	return ""
}

type SendToRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToRes) Reset() {
	*x = SendToRes{}
	mi := &file_blockchain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToRes) ProtoMessage() {}

func (x *SendToRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToRes.ProtoReflect.Descriptor instead.
func (*SendToRes) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{6}
}

func (x *SendToRes) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  AccountType            `protobuf:"varint,1,opt,name=type,proto3,enum=blockchain.AccountType" json:"type,omitempty"`
	Bid   string                 `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_blockchain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{7}
}

func (x *Address) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_Tron
}

func (x *Address) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *Address) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ImportReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Bid                 string      `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	AccountType         AccountType `protobuf:"varint,2,opt,name=accountType,proto3,enum=blockchain.AccountType" json:"accountType,omitempty"`
	EncryptedPrivateKey []byte      `protobuf:"bytes,3,opt,name=EncryptedPrivateKey,proto3" json:"EncryptedPrivateKey,omitempty"`
	EncryptedBy         *Address    `protobuf:"bytes,4,opt,name=EncryptedBy,proto3" json:"EncryptedBy,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ImportReq) Reset() {
	*x = ImportReq{}
	mi := &file_blockchain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportReq) ProtoMessage() {}

func (x *ImportReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportReq.ProtoReflect.Descriptor instead.
func (*ImportReq) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{8}
}

func (x *ImportReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *ImportReq) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_Tron
}

func (x *ImportReq) GetEncryptedPrivateKey() []byte {
	if x != nil {
		return x.EncryptedPrivateKey
	}
	return nil
}

func (x *ImportReq) GetEncryptedBy() *Address {
	if x != nil {
		return x.EncryptedBy
	}
	return nil
}

type ImportRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRes) Reset() {
	*x = ImportRes{}
	mi := &file_blockchain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRes) ProtoMessage() {}

func (x *ImportRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRes.ProtoReflect.Descriptor instead.
func (*ImportRes) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{9}
}

func (x *ImportRes) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type BalanceReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenID         uint32                 `protobuf:"varint,1,opt,name=tokenID,proto3" json:"tokenID,omitempty"`
	NetworkKey      string                 `protobuf:"bytes,2,opt,name=networkKey,proto3" json:"networkKey,omitempty"`
	ContractAddress string                 `protobuf:"bytes,3,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Address         []string               `protobuf:"bytes,4,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BalanceReq) Reset() {
	*x = BalanceReq{}
	mi := &file_blockchain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceReq) ProtoMessage() {}

func (x *BalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceReq.ProtoReflect.Descriptor instead.
func (*BalanceReq) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{10}
}

func (x *BalanceReq) GetTokenID() uint32 {
	if x != nil {
		return x.TokenID
	}
	return 0
}

func (x *BalanceReq) GetNetworkKey() string {
	if x != nil {
		return x.NetworkKey
	}
	return ""
}

func (x *BalanceReq) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BalanceReq) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

type BalanceResItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResItem) Reset() {
	*x = BalanceResItem{}
	mi := &file_blockchain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResItem) ProtoMessage() {}

func (x *BalanceResItem) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResItem.ProtoReflect.Descriptor instead.
func (*BalanceResItem) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{11}
}

func (x *BalanceResItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BalanceResItem) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type BalanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*BalanceResItem      `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRes) Reset() {
	*x = BalanceRes{}
	mi := &file_blockchain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRes) ProtoMessage() {}

func (x *BalanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRes.ProtoReflect.Descriptor instead.
func (*BalanceRes) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{12}
}

func (x *BalanceRes) GetItem() []*BalanceResItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_blockchain_proto protoreflect.FileDescriptor

const file_blockchain_proto_rawDesc = "" +
	"\n" +
	"\x10blockchain.proto\x12\n" +
	"blockchain\"\xd6\x03\n" +
	"\x11BlockchainNetwork\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\achainID\x18\x04 \x01(\tR\achainID\x127\n" +
	"\n" +
	"accountKey\x18\x05 \x01(\x0e2\x17.blockchain.AccountTypeR\n" +
	"accountKey\x12\x18\n" +
	"\adecimal\x18\x06 \x01(\x04R\adecimal\x12&\n" +
	"\x0edisplayDecimal\x18\a \x01(\x04R\x0edisplayDecimal\x12\x12\n" +
	"\x04logo\x18\b \x01(\tR\x04logo\x12\x16\n" +
	"\x06symbol\x18\t \x01(\tR\x06symbol\x12\x1e\n" +
	"\n" +
	"fullSymbol\x18\n" +
	" \x01(\tR\n" +
	"fullSymbol\x12\x1a\n" +
	"\barchType\x18\v \x01(\tR\barchType\x12\x16\n" +
	"\x06rpcURL\x18\f \x03(\tR\x06rpcURL\x12(\n" +
	"\x0fconfirmStrategy\x18\r \x01(\x04R\x0fconfirmStrategy\x120\n" +
	"\x13blockGenerationRate\x18\x0e \x01(\x04R\x13blockGenerationRate\x12\x18\n" +
	"\ascanURL\x18\x0f \x01(\tR\ascanURL\"\x85\x02\n" +
	"\rGenAddressReq\x129\n" +
	"\vaccountType\x18\x01 \x01(\x0e2\x17.blockchain.AccountTypeR\vaccountType\x129\n" +
	"\vaddressType\x18\x02 \x01(\x0e2\x17.blockchain.AddressTypeR\vaddressType\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\tR\x03bid\x12\x12\n" +
	"\x04nums\x18\x04 \x01(\x03R\x04nums\x12\x1a\n" +
	"\bwithUSDT\x18\x05 \x01(\bR\bwithUSDT\x12\x1e\n" +
	"\n" +
	"networkKey\x18\x06 \x01(\tR\n" +
	"networkKey\x12\x1c\n" +
	"\ttokenKind\x18\a \x01(\tR\ttokenKind\")\n" +
	"\rGenAddressRes\x12\x18\n" +
	"\aaddress\x18\x01 \x03(\tR\aaddress\"x\n" +
	"\x0eCollectFundReq\x12\x1e\n" +
	"\n" +
	"networkKey\x18\x01 \x01(\tR\n" +
	"networkKey\x12\x18\n" +
	"\atokenID\x18\x02 \x01(\x04R\atokenID\x12\x12\n" +
	"\x04send\x18\x03 \x03(\tR\x04send\x12\x18\n" +
	"\areceive\x18\x04 \x01(\tR\areceive\"(\n" +
	"\x0eCollectFundRes\x12\x16\n" +
	"\x06txHash\x18\x01 \x03(\tR\x06txHash\"\x8f\x02\n" +
	"\tSendToReq\x12\x1e\n" +
	"\n" +
	"networkKey\x18\x01 \x01(\tR\n" +
	"networkKey\x12\x18\n" +
	"\atokenID\x18\x02 \x01(\x04R\atokenID\x12\x12\n" +
	"\x04send\x18\x03 \x01(\tR\x04send\x12\x18\n" +
	"\areceive\x18\x04 \x01(\tR\areceive\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x04R\x06amount\x12\x14\n" +
	"\x05isOut\x18\x06 \x01(\bR\x05isOut\x12\"\n" +
	"\fbusinessType\x18\a \x01(\tR\fbusinessType\x12\x1c\n" +
	"\tforceSend\x18\b \x01(\bR\tforceSend\x12\x12\n" +
	"\x04memo\x18\t \x01(\tR\x04memo\x12\x16\n" +
	"\x06billID\x18\n" +
	" \x01(\tR\x06billID\"#\n" +
	"\tSendToRes\x12\x16\n" +
	"\x06txHash\x18\x01 \x01(\tR\x06txHash\"\\\n" +
	"\aAddress\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.blockchain.AccountTypeR\x04type\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\tR\x03bid\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\"\xc1\x01\n" +
	"\tImportReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x129\n" +
	"\vaccountType\x18\x02 \x01(\x0e2\x17.blockchain.AccountTypeR\vaccountType\x120\n" +
	"\x13EncryptedPrivateKey\x18\x03 \x01(\fR\x13EncryptedPrivateKey\x125\n" +
	"\vEncryptedBy\x18\x04 \x01(\v2\x13.blockchain.AddressR\vEncryptedBy\":\n" +
	"\tImportRes\x12-\n" +
	"\aaddress\x18\x01 \x01(\v2\x13.blockchain.AddressR\aaddress\"\x8a\x01\n" +
	"\n" +
	"BalanceReq\x12\x18\n" +
	"\atokenID\x18\x01 \x01(\rR\atokenID\x12\x1e\n" +
	"\n" +
	"networkKey\x18\x02 \x01(\tR\n" +
	"networkKey\x12(\n" +
	"\x0fcontractAddress\x18\x03 \x01(\tR\x0fcontractAddress\x12\x18\n" +
	"\aaddress\x18\x04 \x03(\tR\aaddress\"D\n" +
	"\x0eBalanceResItem\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\"<\n" +
	"\n" +
	"BalanceRes\x12.\n" +
	"\x04item\x18\x01 \x03(\v2\x1a.blockchain.BalanceResItemR\x04item*5\n" +
	"\vAccountType\x12\b\n" +
	"\x04Tron\x10\x00\x12\a\n" +
	"\x03Ton\x10\x01\x12\n" +
	"\n" +
	"\x06Solana\x10\x02\x12\a\n" +
	"\x03Bsc\x10\x03*\x15\n" +
	"\aAPIEnum\x12\n" +
	"\n" +
	"\x06SendTx\x10\x00*&\n" +
	"\vAddressType\x12\v\n" +
	"\areceive\x10\x00\x12\n" +
	"\n" +
	"\x06gather\x10\x012\x89\x02\n" +
	"\x10BlockchainServer\x12D\n" +
	"\n" +
	"GenAddress\x12\x19.blockchain.GenAddressReq\x1a\x19.blockchain.GenAddressRes\"\x00\x128\n" +
	"\x06SendTo\x12\x15.blockchain.SendToReq\x1a\x15.blockchain.SendToRes\"\x00\x128\n" +
	"\x06Import\x12\x15.blockchain.ImportReq\x1a\x15.blockchain.ImportRes\"\x00\x12;\n" +
	"\aBalance\x12\x16.blockchain.BalanceReq\x1a\x16.blockchain.BalanceRes\"\x00B6Z4github.com/secure-protocol/protocol/proto/blockchainb\x06proto3"

var (
	file_blockchain_proto_rawDescOnce sync.Once
	file_blockchain_proto_rawDescData []byte
)

func file_blockchain_proto_rawDescGZIP() []byte {
	file_blockchain_proto_rawDescOnce.Do(func() {
		file_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_proto_rawDesc), len(file_blockchain_proto_rawDesc)))
	})
	return file_blockchain_proto_rawDescData
}

var file_blockchain_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_blockchain_proto_goTypes = []any{
	(AccountType)(0),          // 0: blockchain.AccountType
	(APIEnum)(0),              // 1: blockchain.APIEnum
	(AddressType)(0),          // 2: blockchain.AddressType
	(*BlockchainNetwork)(nil), // 3: blockchain.BlockchainNetwork
	(*GenAddressReq)(nil),     // 4: blockchain.GenAddressReq
	(*GenAddressRes)(nil),     // 5: blockchain.GenAddressRes
	(*CollectFundReq)(nil),    // 6: blockchain.CollectFundReq
	(*CollectFundRes)(nil),    // 7: blockchain.CollectFundRes
	(*SendToReq)(nil),         // 8: blockchain.SendToReq
	(*SendToRes)(nil),         // 9: blockchain.SendToRes
	(*Address)(nil),           // 10: blockchain.Address
	(*ImportReq)(nil),         // 11: blockchain.ImportReq
	(*ImportRes)(nil),         // 12: blockchain.ImportRes
	(*BalanceReq)(nil),        // 13: blockchain.BalanceReq
	(*BalanceResItem)(nil),    // 14: blockchain.BalanceResItem
	(*BalanceRes)(nil),        // 15: blockchain.BalanceRes
}
var file_blockchain_proto_depIdxs = []int32{
	0,  // 0: blockchain.BlockchainNetwork.accountKey:type_name -> blockchain.AccountType
	0,  // 1: blockchain.GenAddressReq.accountType:type_name -> blockchain.AccountType
	2,  // 2: blockchain.GenAddressReq.addressType:type_name -> blockchain.AddressType
	0,  // 3: blockchain.Address.type:type_name -> blockchain.AccountType
	0,  // 4: blockchain.ImportReq.accountType:type_name -> blockchain.AccountType
	10, // 5: blockchain.ImportReq.EncryptedBy:type_name -> blockchain.Address
	10, // 6: blockchain.ImportRes.address:type_name -> blockchain.Address
	14, // 7: blockchain.BalanceRes.item:type_name -> blockchain.BalanceResItem
	4,  // 8: blockchain.BlockchainServer.GenAddress:input_type -> blockchain.GenAddressReq
	8,  // 9: blockchain.BlockchainServer.SendTo:input_type -> blockchain.SendToReq
	11, // 10: blockchain.BlockchainServer.Import:input_type -> blockchain.ImportReq
	13, // 11: blockchain.BlockchainServer.Balance:input_type -> blockchain.BalanceReq
	5,  // 12: blockchain.BlockchainServer.GenAddress:output_type -> blockchain.GenAddressRes
	9,  // 13: blockchain.BlockchainServer.SendTo:output_type -> blockchain.SendToRes
	12, // 14: blockchain.BlockchainServer.Import:output_type -> blockchain.ImportRes
	15, // 15: blockchain.BlockchainServer.Balance:output_type -> blockchain.BalanceRes
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_blockchain_proto_init() }
func file_blockchain_proto_init() {
	if File_blockchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_proto_rawDesc), len(file_blockchain_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blockchain_proto_goTypes,
		DependencyIndexes: file_blockchain_proto_depIdxs,
		EnumInfos:         file_blockchain_proto_enumTypes,
		MessageInfos:      file_blockchain_proto_msgTypes,
	}.Build()
	File_blockchain_proto = out.File
	file_blockchain_proto_goTypes = nil
	file_blockchain_proto_depIdxs = nil
}
